
server:
  applicationContextPath: /api
  adminContextPath: /admin
  requestLog:
    appenders:
      - type: console

      - type: file
        currentLogFilename: ./logs/ncfinder-access.log
        archivedLogFilenamePattern: ./logs/ncfinder-access-%d.log.gz
        timeZone: UTC

# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  #driverClass: com.mysql.cj.jdbc.Driver
  # the username
  #user: ncfinder
  # the password
  #password: projeto
  # the JDBC URL; the database is called DWGettingStarted
  #url: jdbc:mysql://localhost:3306/ncfinder?serverTimezone=UTC

  #ORIGINAL
  #driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #url: jdbc:sqlserver://dcdeadcd-7ddb-447e-9f4b-ab1000bd996d.sqlserver.sequelizer.com:1433;d‌​atabaseName=dbdcdeadcd7ddb447e9f4bab1000bd996d;user=unujmrbnjvvfcdqw;password=GyFjuuBVod8VnBLU3t3StJRkYFJ5LEziJrVimhRAebizQqu4nfsUn4J7QutWTFjQ;

  #VAAM
  driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://db:1433;Database=ncfinderdb;user=sa;password=Your_password123

  #properties:
      #hibernate.hbm2ddl.auto: create

# Database settings.
#database:
#  # the name of the JDBC driver, mysql in our case
#  driverClass: com.mysql.cj.jdbc.Driver
#  # the username
#  user: ncfinder
#  # the password
#  password: projeto
#  # the JDBC URL; the database is called DWGettingStarted
#  url: jdbc:mysql://localhost:3306/ncfinder?serverTimezone=UTC
#  properties:
#    hibernate.hbm2ddl.auto: create
    
swagger:
  resourcePackage: projeto.resources

logging:
  level: INFO
  loggers:
    projeto: DEBUG

  appenders:
    # Log warnings and errors to stderr
    - type: console
      threshold: INFO
      target: stdout

    # Log info, warnings and errors to our apps' main log.
    # Rolled over daily and retained for 5 days.
    - type: file
      threshold: DEBUG
      currentLogFilename: ./logs/ncfinder.log
      archivedLogFilenamePattern: ./logs/ncfinder-%d.log.gz
      archivedFileCount: 7
      timeZone: UTC

    - type: file
      threshold: WARN
      currentLogFilename: ./logs/ncfinder-warning-error.log
      archivedLogFilenamePattern: ./logs/ncfinder-error-%d.log.gz
      archivedFileCount: 7
      timeZone: UTC

    - type: file
      threshold: ERROR
      currentLogFilename: ./logs/ncfinder-error.log
      archivedLogFilenamePattern: ./logs/ncfinder-error-%d.log.gz
      archivedFileCount: 7
      timeZone: UTC

    #database:
  # the name of your JDBC driver
  #driverClass: org.postgresql.Driver
  # the username
  #user: postgres
  # the password
  #password: postgres
  # the JDBC URL
  #url: jdbc:postgresql://localhost/ncfinder
  # any properties specific to your JDBC driver:
  #properties:
    #hibernate.hbm2ddl.auto: create

#VAAM
sundial:
  annotated-jobs-package-name: projeto.job
