USE [dbdcdeadcd7ddb447e9f4bab1000bd996d]
GO

/****** Object:  Table [dbo].[USERS]    Script Date: 03/05/2020 13:26:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERS](
	[username] [varchar](200) NOT NULL,
	[password] [varchar](1000) NOT NULL,
	[role] [varchar](100) NULL,
	[name] [varchar](300) NULL,
	[email] [varchar](300) NULL,
	[rfid] [varchar](100) NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_USERS_ROLES] FOREIGN KEY([role])
REFERENCES [dbo].[ROLES] ([name])
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_USERS_ROLES]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_USERS_TAGS] FOREIGN KEY([rfid])
REFERENCES [dbo].[TAGS] ([rfid])
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_USERS_TAGS]
GO

