USE [dbdcdeadcd7ddb447e9f4bab1000bd996d]
GO

/****** Object:  Table [dbo].[EVENTS]    Script Date: 03/05/2020 13:25:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EVENTS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[caseId] [bigint] NULL,
	[duration] [bigint] NOT NULL,
	[endDate] [datetime2](7) NULL,
	[name] [varchar](300) NULL,
	[resource] [varchar](200) NULL,
	[role] [varchar](100) NULL,
	[startDate] [datetime2](7) NULL,
	[LOG_ID] [bigint] NULL,
	[partCode] [varchar](100) NULL,
	[processId] [bigint] NULL,
	[isEstimatedEnd] [bit] NULL,
	[mouldCode] [varchar](100) NULL,
	[username] [varchar](200) NULL,
	[activityId] [bigint] NULL,
 CONSTRAINT [PK_EVENTS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_duration]  DEFAULT ((0)) FOR [duration]
GO

ALTER TABLE [dbo].[EVENTS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_ACTIVITIES] FOREIGN KEY([activityId])
REFERENCES [dbo].[ACTIVITIES] ([id])
GO

ALTER TABLE [dbo].[EVENTS] CHECK CONSTRAINT [FK_EVENTS_ACTIVITIES]
GO

ALTER TABLE [dbo].[EVENTS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_MOULDS] FOREIGN KEY([mouldCode])
REFERENCES [dbo].[MOULDS] ([code])
GO

ALTER TABLE [dbo].[EVENTS] CHECK CONSTRAINT [FK_EVENTS_MOULDS]
GO

ALTER TABLE [dbo].[EVENTS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_PARTS] FOREIGN KEY([partCode])
REFERENCES [dbo].[PARTS] ([code])
GO

ALTER TABLE [dbo].[EVENTS] CHECK CONSTRAINT [FK_EVENTS_PARTS]
GO

ALTER TABLE [dbo].[EVENTS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_PROCESSES] FOREIGN KEY([processId])
REFERENCES [dbo].[PROCESSES] ([id])
GO

ALTER TABLE [dbo].[EVENTS] CHECK CONSTRAINT [FK_EVENTS_PROCESSES]
GO

ALTER TABLE [dbo].[EVENTS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_USERS] FOREIGN KEY([username])
REFERENCES [dbo].[USERS] ([username])
GO

ALTER TABLE [dbo].[EVENTS] CHECK CONSTRAINT [FK_EVENTS_USERS]
GO

ALTER TABLE [dbo].[EVENTS]  WITH CHECK ADD  CONSTRAINT [FKro808iycxm1vfukekdwla0o1b] FOREIGN KEY([LOG_ID])
REFERENCES [dbo].[LOGS] ([id])
GO

ALTER TABLE [dbo].[EVENTS] CHECK CONSTRAINT [FKro808iycxm1vfukekdwla0o1b]
GO

