USE [dbdcdeadcd7ddb447e9f4bab1000bd996d]
GO

/****** Object:  Table [dbo].[ACTIVITIES]    Script Date: 03/05/2020 13:23:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ACTIVITIES](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[name] [varchar](300) NOT NULL,
	[description] [varchar](1000) NULL,
	[isTagging] [bit] NULL,
	[isEndActivity] [bit] NULL,
	[subprocessId] [bigint] NULL,
 CONSTRAINT [PK_ACTIVITIES] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ACTIVITIES]  WITH CHECK ADD  CONSTRAINT [FK_ACTIVITIES_PROCESSES] FOREIGN KEY([subprocessId])
REFERENCES [dbo].[PROCESSES] ([id])
GO

ALTER TABLE [dbo].[ACTIVITIES] CHECK CONSTRAINT [FK_ACTIVITIES_PROCESSES]
GO

