USE [dbdcdeadcd7ddb447e9f4bab1000bd996d]
GO

/****** Object:  Table [dbo].[ESPS]    Script Date: 03/05/2020 13:24:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ESPS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[mac] [nvarchar](100) NULL,
	[activityId] [bigint] NULL,
 CONSTRAINT [PK_ESPS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ESPS]  WITH CHECK ADD  CONSTRAINT [FK_ESPS_ACTIVITIES] FOREIGN KEY([id])
REFERENCES [dbo].[ACTIVITIES] ([id])
GO

ALTER TABLE [dbo].[ESPS] CHECK CONSTRAINT [FK_ESPS_ACTIVITIES]
GO

