USE [dbdcdeadcd7ddb447e9f4bab1000bd996d]
GO

/****** Object:  Table [dbo].[ACTIVITIES]    Script Date: 05/04/2020 01:53:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ACTIVITIES](
	[name] [varchar](300) NOT NULL,
	[description] [varchar](1000) NULL,
	[tagging] [bit] NULL,
	[end_activity] [bit] NULL,
 CONSTRAINT [PK_ACTIVITIES] PRIMARY KEY CLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

