USE dbdcdeadcd7ddb447e9f4bab1000bd996d
GO

/****** Object:  Table [dbo].[MOULDS]    Script Date: 24/03/2020 23:31:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOULDS](
	[code] [varchar](100) NOT NULL,
	[description] [varchar](300) NULL,
 CONSTRAINT [PK_Moulds] PRIMARY KEY CLUSTERED 
(
	[code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

