USE dbdcdeadcd7ddb447e9f4bab1000bd996d
GO

/****** Object:  Table [dbo].[USERS_WORKSTATIONS]    Script Date: 25/03/2020 01:19:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERS_WORKSTATIONS](
	[id_user] [bigint] NOT NULL,
	[id_workstation] [bigint] NOT NULL,
 CONSTRAINT [PK_USERS_WORKSTATIONS] PRIMARY KEY CLUSTERED 
(
	[id_user] ASC,
	[id_workstation] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

